core:
  cluster-api:
    manager:
      featureGates:
        ClusterTopology: true
bootstrap:
  kubeadm:
    manager:
      featureGates:
        ClusterTopology: true
controlPlane:
  kubeadm:
    manager:
      featureGates:
        ClusterTopology: true
infrastructure: 
  gcp: 
    enabled: true
    version: "v1.11.0"
    manager:
      featureGates:
        ClusterTopology: true
configSecret:
  name: gcp-credentials
  namespace: default
